apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  # lables aof deployment resource
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      purpose: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        purpose: expense
    spec:
      containers:
      - name: nginx
        image: pavanreddy143/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector: # labels are used as selectors
    app: mysql
    tier: mysql
    purpose: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306